version: '3'

volumes:
  pg_data_kit:
  static_kit:
  media_kit:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_kit:/var/lib/postgresql/data/
  backend:
    image: wolf7201/kittygram_backend
    env_file: .env
    volumes:
      - static_kit:/backend_static/
      - media_kit:/var/www/kittygram/media/
    depends_on:
      - db
  frontend:
    image: wolf7201/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_kit:/frontend_static/
  gateway:
    image: wolf7201/kittygram_gateway
    volumes:
      - static_kit:/static/
      - media_kit:/var/www/kittygram/media:ro
    ports:
      - 9000:80